name: sga
services:
  web:
    image: nginx:alpine
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./nginx/app.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - frontend-net
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: apipass
      POSTGRES_DB: api
      POSTGRES_USER: apiuser
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend-net
  
  api:
    image: sga:${APP_VERSION:-latest}
    build: ./simple-golang-api
    environment:
      API_DB_HOST: db
      API_DB_PORT: 5432
      API_DB_PASS: apipass
      API_DB_NAME: api
      API_DB_USER: apiuser
    networks:
      - frontend-net
      - backend-net
    scale: 2
    depends_on:
      db:
        condition: service_started
        restart: true
networks:
  frontend-net:
  backend-net:

volumes:
  dbdata: